### ISSUE TITLE
请教下，具体如何操作

### ISSUE THREAD

**Issue by dandan7675** [M4tsuri/Surge_Crack#3]
请大神具体指导下啊

**Comment by m4tsuri** [comment]
谢邀已经入正了，如果是冲着破解来的话建议放弃，似乎还有一些细小的地方没有完全破解，有时候会出问题。

**Comment by yizhimuzhuozi** [comment]
已入正版。


M4tsuri ***@***.***> 于 2022年6月4日周六 00:22写道：
